### ISSUE TITLE
Wrong original DSS project license

### ISSUE THREAD

**Issue by ceztko** [nonorganic/dssnet#5]
The original DSS license is LGPL 2.1, as pointed here[1], not GPL 2.0 as pointed in your license [page](https://github.com/nonorganic/dssnet/blob/master/LICENSE.md). This is also mentioned in all source files headers, that specifically refer to "GNU Lesser General Public License". I think it was just an oversight, but better it to get it fixed to expose correct license terms to everybody.

As a side question: is this project tested/used in production? Thanks

[1] https://github.com/esig/dss/blob/master/LICENSE

**Comment by nonorganic** [comment]
Thanks for your comment. I actually used this code for a real paid project several years ago and worked without major issues.

However I haven't continued support of this repo. It would be nice to translate again the most recent DSS to. NET Core but I think Java is good enough for every purpose: mobile, desktop, server, etc.

You can even use a bridge between Java and Net Core and call the DSS library. Or better, expose DSS as a microservice and call it from everywere (scala, python, etc.)

What do you think about continuing this repo?

**Comment by nonorganic** [comment]
Thanks for your comment. I actually used this code for a real paid project several years ago and worked without major issues.

However I haven't continued support of this repo. It would be nice to translate again the most recent DSS to. NET Core but I think Java is good enough for every purpose: mobile, desktop, server, etc.

You can even use a bridge between Java and Net Core and call the DSS library. Or better, expose DSS as a microservice and call it from everywere (scala, python, etc.)

What do you think about continuing this repo?

**Comment by ceztko** [comment]
I created a pull request to fix the license info.

So far I am just evaluating dssnet: I was [able ](https://github.com/ceztko/dssnet/tree/NetStandard)to remove iTextSharp (for licensing problems) and compile to .NET standard 2.0 (for environment requirements), just to ensure I can actually afford it. Can you provide me a one-liner to sign a file with CAdES-BES? After I should be autonomous.

It's a bit early to tell if I'm going to maintain the project, but yes: like you I am paid to insert some signing functionalities in a product and Java is not an option for me. It's a pity BouncyCastle was forked for the scope of the project. The amount of modifications doesn't seems huge, though.

**Comment by nonorganic** [comment]
Sure, documentation is here: https://github.com/nonorganic/dssnet/blob/master/DSS3-T1-CookBook-v1.05.doc

I kept the same classes, so it could be helpful if you give it a look.

Here attached some test files also, I hope those would help you a bit more. Those were made to test CAdES-C, but feel free to remove CRL and OCSP to create a simple CAdES-BES

[Cades test example.zip](https://github.com/nonorganic/dssnet/files/5381939/Cades.test.example.zip)

Let me know if you need any further info.

**Comment by ceztko** [comment]
I was successful in testing the sample. My next attempt was to remove the bundled BouncyCastle: I understood you had some troubles in plugging an external signer, but the BC api seems to be improved now. I almost succeeded but I ended with an half valid .p7m that can't verify the digest. 

I wanted to ask you: are you available for hire to work on this project again? Can you give me your email?

**Comment by nonorganic** [comment]
I am glad you could successfully test the sample. I have a full-time job now so I do not think I have enough free time now, but you can write me with confidence: josebonillapazmino@gmail.com
